id_name:
  0: node0
  1: node1
  2: node2
  3: node3
id_ip:
  0: 10.0.2.15
  1: 10.0.2.15
  2: 10.0.2.15
  3: 10.0.2.15
id_p2p_port:
  0: 9000
  1: 9001
  2: 9002
  3: 9003
log_level: 3
max_pool: 10
timeout: 5
network_delay: 10
ddos: false
max_payload_size: 5000
max_payload_count: 100
rate: 1000
tx_size: 512