- hosts: parbft
  remote_user: vagrant
  gather_facts: no
  tasks:
    - name: create testbed dirs
      file:
        path: /home/vagrant/{{inventory_hostname}}/parbft-testbed
        state: directory
    - name: run parbft as a daemon
      shell: "(nohup ./parbft > /home/vagrant/{{inventory_hostname}}/parbft-testbed/log0.txt 2>&1 &)"
      args:
        chdir: /home/vagrant/{{inventory_hostname}}/parbft